vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
       product:
           uri_prefix: /images/product
           upload_destination: '%kernel.project_dir%/public/images/product'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
